name: scale-scope
version: 0.2.0
synopsis: View 3D models and animation sequences
license: MIT
license-file: LICENSE
author: doublescale
maintainer: doublescale@tutanota.com

flags:
  debug:
    description: Fewer warnings, less optimization
    default: false
    manual: true

ghc-options:
  - -threaded
  - -rtsopts

when:
  - condition: flag(debug)
    then:
      ghc-options:
        - -fdefer-type-errors
    else:
      ghc-options:
        - -Wall
        - -Werror
        - -O2

dependencies:
  - base
  - bytestring
  - containers
  - directory
  - filepath
  - ghc-prim
  - half
  - linear
  - store
  - vector
  - zlib

default-extensions:
  - DeriveAnyClass
  - FlexibleContexts
  - DeriveGeneric
  - NamedFieldPuns
  - RecordWildCards
  - ScopedTypeVariables

source-dirs: src

executables:
  scale-scope:
    main: Main.hs
    dependencies:
      - lens
      - mtl
      - OpenGL
      - sdl2
    other-modules:
      - Action
      - AppState
      - Event
      - Event.ModState
      - Mesh
      - Render
      - Render.Mesh
      - Render.Shader
      - Render.Texture
      - Render.Types
      - Util
  scale-pack:
    main: MainPack.hs
    dependencies:
      - attoparsec
      - JuicyPixels
      - optparse-applicative
    other-modules:
      - Mesh
      - MeshConversion
      - OBJParser
